name: ae Backend Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ secrets.NODE_ENV || 'development' }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10'
          run_install: false

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build Project
        run: pnpm build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Upload .env to EC2
        run: |
          printf "%s" "${{ secrets.PROD_ENV_FILE }}" > .env
          scp -i ~/.ssh/id_rsa .env ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }}:~/backend/
          rm -f .env

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} "mkdir -p ~/backend"
          rsync -az --delete \
            --exclude ".git" \
            --exclude "node_modules" \
            -e "ssh -i ~/.ssh/id_rsa" \
           ./ ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }}:~/backend/
          EOF

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/id_rsa ${{ env.EC2_USERNAME }}@${{ env.EC2_HOST }} << 'EOF'
            curl -s http://localhost:4000/api/health | grep '"status":"ok"' || exit 1
          EOF
